name: build-ipk

on:
#  schedule:
#    - cron: 5 6 * * 0
  workflow_dispatch:
  #watch:
    #types: started
    
env:
  REPO_TOKEN: ${{ secrets.workflow_token }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          fetch-depth: 0
          
    - name: Free disk space
      uses: coder-xiaomo/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Init build dependencies
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
          sudo -E apt-get -qq update
          sudo /bin/bash -c "$(curl -sL https://git.io/vokNn)"
          sudo -E apt-fast -y -qq install asciidoc bash bcc bin86 binutils bison bzip2 clang file flex g++ g++-multilib gawk gcc-multilib gettext git gzip help2man intltool libbpf-dev libboost-dev libelf-dev libncurses-dev libssl-dev libthread-queue-any-perl libusb-dev libxml-parser-perl linux-tools-generic llvm make patch perl-modules pkg-config python3-dev python3-pip python3-pyelftools python3-setuptools rsync sharutils swig time unzip util-linux wget xsltproc zlib1g-dev zip zstd
          sudo -E apt-fast -y -qq install dos2unix dwarves jq npm quilt
          sudo -E npm install -g pnpm
          sudo -E npm install -g n
          sudo -E n stable
          pip3 install --user -U pylibfdt --break-system-packages
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'
          sudo -E git config --global core.abbrev auto
          df -h
          
    - name: clone openwrt
      run: |
        #sudo chown -R runner:runner /home/runner/work/OprX-oR-gargoyle-YAOF
        git clone --single-branch -b v24.10.5 https://github.com/openwrt/openwrt openwrt
        
    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/openwrt/build_dir openwrt/staging_dir
        ln -sf /mnt/openwrt/build_dir openwrt/build_dir
        sudo ln -sf openwrt/staging_dir /mnt/openwrt/staging_dir

    - name: Prepare ipk
      working-directory: ${{ github.workspace }}/openwrt
      run: |
          cp -r ../ipk.sh ./
          chmod 0755 ipk.sh
          /bin/bash ipk.sh
          
    - name: Install Feeds
      working-directory: ${{ github.workspace }}/openwrt
      run: |
          ./scripts/feeds clean
          ./scripts/feeds update -a
          ./scripts/feeds install -a   
  
    - name: import config
      working-directory: ${{ github.workspace }}/openwrt
      run: |
          cp -rf ../ipk.config .config

    - name: make config
      working-directory: ${{ github.workspace }}/openwrt
      run: |
          #cd openwrt
          make defconfig
        
    - name: Make Download
      working-directory: ${{ github.workspace }}/openwrt
      run: |
        make download -j50
        
    - name: Compile Openwrt
      working-directory: ${{ github.workspace }}/openwrt
      id: compileopenwrt
      continue-on-error: true
      run: |
        #echo | make kernel_oldconfig -j$(($(nproc) + 1)) 
        GNORE_ERRORS=1 make -j$(($(nproc) + 1))
        echo $?

    - name: If Error
      working-directory: ${{ github.workspace }}/openwrt
      if: steps.compileopenwrt.outcome == 'failure'
      run: |
        cat ./.config
        echo '================================================================'
        make -j1 V=s
        
    - name: Organize ipk
      id: organize
      run: |
        rm -rf ./ipk/
        mkdir -p ./ipk
        find openwrt/bin/packages/*/*  -name "*qos-gargoyle*" | xargs -i mv -f {} ipk/
     
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@main
      with:
        name: qos-gargoyle
        allowUpdates: true
        prerelease: false
        tag: ipk
        commit: "main"  #对应分支
        replacesArtifacts: true
        token: ${{ secrets.workflow_token }}
        artifacts: ./ipk/*
        
    - name: Print Disk Space After
      run: df -h
